services:
  - type: web
    name: wisdomai-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://wisdomai.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: knowledge-base
      mountPath: /opt/render/project/src/knowledge
      sizeGB: 1 